---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-v1
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
      version: v1
  template:
    metadata:
      labels:
        app: first-app
        version: v1
        istio: monitor
        #  sidecar.istio.io/inject: "true" - to spesific sidecar this deployment
    spec:
      containers:
        - image: giler053/myapp:latest
          imagePullPolicy: Always
          name: first-app
          env:
            - name: SERVICE
              value: first-app
            - name: VERSION
              value: v1
          ports:
            - name: http
              containerPort: 8080